# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/gurth/Software/CLion/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/gurth/Software/CLion/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gurth/Workstation/etc/gasm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gurth/Workstation/etc/gasm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/gurth/Software/CLion/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/gurth/Software/CLion/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gurth/Workstation/etc/gasm/CMakeFiles /home/gurth/Workstation/etc/gasm/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gurth/Workstation/etc/gasm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gasm

# Build rule for target.
gasm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gasm
.PHONY : gasm

# fast build rule for target.
gasm/fast:
	$(MAKE) -f CMakeFiles/gasm.dir/build.make CMakeFiles/gasm.dir/build
.PHONY : gasm/fast

error.o: error.cpp.o

.PHONY : error.o

# target to build an object file
error.cpp.o:
	$(MAKE) -f CMakeFiles/gasm.dir/build.make CMakeFiles/gasm.dir/error.cpp.o
.PHONY : error.cpp.o

error.i: error.cpp.i

.PHONY : error.i

# target to preprocess a source file
error.cpp.i:
	$(MAKE) -f CMakeFiles/gasm.dir/build.make CMakeFiles/gasm.dir/error.cpp.i
.PHONY : error.cpp.i

error.s: error.cpp.s

.PHONY : error.s

# target to generate assembly for a file
error.cpp.s:
	$(MAKE) -f CMakeFiles/gasm.dir/build.make CMakeFiles/gasm.dir/error.cpp.s
.PHONY : error.cpp.s

init.o: init.cpp.o

.PHONY : init.o

# target to build an object file
init.cpp.o:
	$(MAKE) -f CMakeFiles/gasm.dir/build.make CMakeFiles/gasm.dir/init.cpp.o
.PHONY : init.cpp.o

init.i: init.cpp.i

.PHONY : init.i

# target to preprocess a source file
init.cpp.i:
	$(MAKE) -f CMakeFiles/gasm.dir/build.make CMakeFiles/gasm.dir/init.cpp.i
.PHONY : init.cpp.i

init.s: init.cpp.s

.PHONY : init.s

# target to generate assembly for a file
init.cpp.s:
	$(MAKE) -f CMakeFiles/gasm.dir/build.make CMakeFiles/gasm.dir/init.cpp.s
.PHONY : init.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/gasm.dir/build.make CMakeFiles/gasm.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/gasm.dir/build.make CMakeFiles/gasm.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/gasm.dir/build.make CMakeFiles/gasm.dir/main.cpp.s
.PHONY : main.cpp.s

process.o: process.cpp.o

.PHONY : process.o

# target to build an object file
process.cpp.o:
	$(MAKE) -f CMakeFiles/gasm.dir/build.make CMakeFiles/gasm.dir/process.cpp.o
.PHONY : process.cpp.o

process.i: process.cpp.i

.PHONY : process.i

# target to preprocess a source file
process.cpp.i:
	$(MAKE) -f CMakeFiles/gasm.dir/build.make CMakeFiles/gasm.dir/process.cpp.i
.PHONY : process.cpp.i

process.s: process.cpp.s

.PHONY : process.s

# target to generate assembly for a file
process.cpp.s:
	$(MAKE) -f CMakeFiles/gasm.dir/build.make CMakeFiles/gasm.dir/process.cpp.s
.PHONY : process.cpp.s

translate.o: translate.cpp.o

.PHONY : translate.o

# target to build an object file
translate.cpp.o:
	$(MAKE) -f CMakeFiles/gasm.dir/build.make CMakeFiles/gasm.dir/translate.cpp.o
.PHONY : translate.cpp.o

translate.i: translate.cpp.i

.PHONY : translate.i

# target to preprocess a source file
translate.cpp.i:
	$(MAKE) -f CMakeFiles/gasm.dir/build.make CMakeFiles/gasm.dir/translate.cpp.i
.PHONY : translate.cpp.i

translate.s: translate.cpp.s

.PHONY : translate.s

# target to generate assembly for a file
translate.cpp.s:
	$(MAKE) -f CMakeFiles/gasm.dir/build.make CMakeFiles/gasm.dir/translate.cpp.s
.PHONY : translate.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gasm"
	@echo "... error.o"
	@echo "... error.i"
	@echo "... error.s"
	@echo "... init.o"
	@echo "... init.i"
	@echo "... init.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... process.o"
	@echo "... process.i"
	@echo "... process.s"
	@echo "... translate.o"
	@echo "... translate.i"
	@echo "... translate.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

